### Pass test ------------------------------------------------------------------

# type
expect_silent(check_num_int(2))
expect_silent(check_num_int(2L))
expect_silent(check_num_int(c(1, 2, 3)))
expect_silent(check_num_int(as.integer(c(1, 2, 3))))

# allowNULL (Exception from e.g. character)
expect_silent(check_num_int(NULL, allowNULL = TRUE))

### Errors ---------------------------------------------------------------------

# var
expect_error(check_num_int())

# allowNULL
expect_error(
  check_num_int(id, allowNULL = "x"),
  class = "check_num_int_allowNULL_error"
)
expect_error(
  check_num_int(id, allowNULL = NULL),
  class = "check_num_int_allowNULL_error"
)
expect_error(
  check_num_int(id, allowNULL = 12),
  class = "check_num_int_allowNULL_error"
)

# individual error generated by function
expect_error(check_num_int(data), class = "eval_data_error")
expect_error(check_num_int(data), class = "rlang_error")
expect_error(check_num_int(NULL), class = "eval_NULL_error")
expect_error(check_num_int(NULL), class = "rlang_error")
expect_error(check_num_int(NULL, allowNULL = FALSE), class = "eval_NULL_error")
expect_error(check_num_int(NULL, allowNULL = FALSE), class = "rlang_error")

id <- "chr"
err <- tryCatch(check_num_int(id, allowNULL = FALSE), error = function(err) err)
expect_true(rlang::inherits_all(err, c("eval_id_error", "rlang_error")))
expect_equal(err$value, "chr")
expect_equal(err$current_class, "character")

# check typical use in function
fun <- function(x) {
  testr::check_num_int(x, allowNULL = TRUE)
  TRUE
}
expect_true(fun(c(1, 2)))
expect_true(fun(c(2L, -3L)))
expect_true(fun(NULL))
expect_error(
  fun("1"),
  class = "fun_x_error",
  pattern = "`x` must be numeric or integer, not of class \"character\"\\."
)
