name: R-CMD-Production

on:
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    container: thfuchs/ghactions:shiny
    
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Query R package dependencies
        run: |
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")'
        
      - name: Upload check results
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-results
          path: check
